Du list once a day
endavainterns2016/WeatherApp pull request #16
Opened 2016-11-02 10:56 UTC by CebotariM

limited automatic requests for info at 24h

2016-11-02 12:51 UTC, croitor-ivan commented
Resolve conflicts, i still see 2 commits in one PR, why?

2016-11-02 20:39 UTC, MaximCeban requested changes

2016-11-02 20:39 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/ForecastActivity.java
>          ForecastPresenter forecastPresenter = new ForecastPresenter(retrofitFactory, greenDaoFactory, this);
what is the point of creating a local variable and then assign it to global variable???

2016-11-02 20:39 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/utils/TemperatureScales.java
> +        return 273;
what a hell is this? why do you use method to return int value? by the context it should be a constant, and  be accessed   through classname.CONSTANT_NAME

2016-11-02 20:39 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/utils/SharedPrefs.java
> +        } else return false;
if you are using **if else** clause then you have to use braces, please pay attention on this.
 `if(someClause){
  doSmth();
} else{
doBestSmth();
}`

2016-11-02 20:39 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/adapter/RecyclerViewAdapter.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N)
if you are using if else clause then you have to use braces, please pay attention on this.

2016-11-02 20:39 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/ForecastActivity.java
> +        recycleViewAdapter = new RecyclerViewAdapter(cityList, TemperatureScales.getCelsiusScale(), this);
Constants should be accessed through **ClassName.CONSTANT_NAME**, not through methods.

2016-11-02 21:18 UTC, MaximCeban commented
Also please, pay attention on develop branch, It hasn't contain any idea folder and package dao, there is no reason to push your version of that files, remove them and make force push to your branch.

2016-11-03 07:39 UTC, CebotariM commented on app/src/main/java/com/example/nvdovin/weatherapp/ForecastActivity.java
>          ForecastPresenter forecastPresenter = new ForecastPresenter(retrofitFactory, greenDaoFactory, this);
greenDaoFactory is a global variable, i create it in onCreate method, and assign it to global for usage in another method

2016-11-03 07:50 UTC, endavainterns2016 commented on app/src/main/java/com/example/nvdovin/weatherapp/ForecastActivity.java
>          ForecastPresenter forecastPresenter = new ForecastPresenter(retrofitFactory, greenDaoFactory, this);
why don't you initialise it without any intermediate variable?  @MaximCeban

2016-11-03 08:35 UTC, closed without merging