US5 - Automatic update not more frequent than 24h
endavainterns2016/WeatherApp pull request #19
Opened 2016-11-03 08:43 UTC by CebotariM

#Added SharedPrefs
#Edited ForecastActivity

2016-11-03 09:24 UTC, croitor-ivan commented on app/src/main/java/com/example/nvdovin/weatherapp/utils/TemperatureScales.java
> +    public static final int CELSIUS_SCALE = 273;
wtf? parca am zsi fara constante.....

2016-11-03 09:33 UTC, CebotariM commented on app/src/main/java/com/example/nvdovin/weatherapp/utils/TemperatureScales.java
> +    public static final int CELSIUS_SCALE = 273;
Clasa va fi editata ulterior cand se va adauga Fahrenheit. Pana atunci am nevoie de valoarea data

2016-11-03 17:05 UTC, MaximCeban requested changes

2016-11-03 17:05 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/utils/SharedPrefs.java
> +                System.currentTimeMillis() - sharedPref.getLong(LAST_UPDATE_TIME_KEY, 0) > TimeUnit.HOURS.toMillis(TIME_SINCE_LAST_UPDATE))) {
`sharedPref.getLong(LAST_UPDATE_TIME_KEY, 0)` code duplicate, please replace it with local variable.

2016-11-03 17:05 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/utils/SharedPrefs.java
> +            setLastUpdateTime();
why do you use this method here? you check time  and  refresh updated time, this is logically incorrect. You should use `setLastUpdatedTime()` in code after you update weather data. Remove it from here.

2016-11-04 09:08 UTC, croitor-ivan commented on app/src/main/java/com/example/nvdovin/weatherapp/utils/SharedPrefs.java
> +        if ((getLastUpdateTime == 0 ||
????

2016-11-04 13:07 UTC, closed without merging