Add Weather History Logic
endavainterns2016/WeatherApp pull request #24
Opened 2016-11-14 15:25 UTC by VdovinN

2016-11-16 08:57 UTC, victorjimbei requested changes

2016-11-16 08:57 UTC, victorjimbei commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/factory/GreenDaoFactory.java
> +            List<WeatherData> weatherList = getWeatherDataForDay(cityId, dt, 86400L);
You have declared on top DAY_IN_MILLISECONDS_INCLUSIVE, why not to use it here?

And do the same please with others hardcoded values from this method.(178, 378, 1000)

2016-11-16 08:57 UTC, victorjimbei commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/DateConvertor.java
> +        return new Date(dt*1000);
you have declared MILI_VALUE = 1000, let's replace also this hardcoded value.

2016-11-16 08:57 UTC, victorjimbei commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/time/TimeUtils.java
> +        Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
"UTC" may also be retrieved in a constant a reused along the entire class, something like "UTC_TIMEZONE_ID"

2016-11-16 08:57 UTC, victorjimbei commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/time/TimeUtils.java
> +        Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
the comment above apply here too

2016-11-16 08:57 UTC, victorjimbei commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/main/MainActivity.java
> +        //startActivity(testIntent);
I didn't pay any attention to commented code, however formatting the code before commit is very well appreciated ;)

2016-11-16 08:57 UTC, victorjimbei commented on app/src/main/res/layout/city_details_fragment.xml
> +        android:textSize="73sp"/>
Please store all dimensions in dimens file. 
This apply for all xml files below.

2016-11-17 11:20 UTC, MaximCeban requested changes

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/design/ImageUtils.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N)
use braces

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/temperature/TemperatureConvertorInterface.java
> +public interface TemperatureConvertorInterface {
try to avoid using Interface in class or interface name.

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/temperature/TemperatureUtils.java
> +    public static String convertToScale(int kelvin, Context context) {
could you tell me please why you created new class with static method only for adding String.valueOf(another class with static method logic)?

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/temperature/TemperatureUtils.java
> +    private static final char DEGREES_SYMBOL = (char) 0x00B0;
try to keep all string resources in res directory, you write app not a library. you have to use options that Android OS provides in the right way.

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/time/TimeUtils.java
> +    private static final String UTC = "UTC";
I guess this is utc_timezone?

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/history/adapter/HistoryViewPagerAdapter.java
> +        timestampList = cityDate.getTimestamp();
getTimestamp() does it return list? if it is, then why it called like it returns just a value(not collection)?

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/history/adapter/HistoryViewPagerAdapter.java
> +        } else if (position == timestampList.size() - 2) {
'2' - this unknown value has to be named

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/history/adapter/HistoryViewPagerAdapter.java
> +    private static final String TODAY = "TODAY";
could you tell me why you use here and below static String

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/history/grid/GridHistoryFragment.java
> +        if (updatedWeatherDataList.size() == EMPTY_LIST) {
https://docs.oracle.com/javase/7/docs/api/java/util/List.html#isEmpty()

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/main/weather/forecast/ForecastPresenter.java
> +        this.forecastView = view;
this is no reason to use "this"

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/main/weather/forecast/ForecastView.java
> +
empty space
remove it

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/main/weather/forecast/MainRecyclerForecastFragment.java
> +        recyclerView = new RecyclerView(view.getContext());
does it make sense?

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/main/weather/forecast/MainRecyclerForecastFragment.java
> +        forecastPresenter = new ForecastPresenter(this, view.getContext());
could you explain why  you takes this context?

2016-11-17 11:20 UTC, MaximCeban commented on app/src/main/res/layout/grid_item_layout.xml
> +        android:textSize="18sp"
hardcoded value

2016-11-17 11:22 UTC, MaximCeban commented
Could you please read carefully comments I'd left and come with explanation.

2016-11-17 13:15 UTC, victorjimbei commented on app/src/main/res/layout/grid_history_layout.xml
> +    android:background="#00FFFFFF"
please use it from colors

2016-11-17 13:16 UTC, victorjimbei commented on app/src/main/res/layout/forecast_recycler_row.xml
> +    android:background="#80000000"
also this values #80000000 and 10dp

2016-11-17 13:54 UTC, victorjimbei approved these changes

2016-11-17 15:50 UTC, MaximCeban requested changes

2016-11-17 15:50 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/history/grid/GridHistoryFragment.java
> +    public static final int EMPTY_LIST = 0;
unused variable

2016-11-17 15:50 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/presentation/main/weather/forecast/adapter/ForecastRecyclerViewAdapter.java
> +        View itemView;
redundant variable

2016-11-17 16:02 UTC, MaximCeban approved these changes

2016-11-17 16:02 UTC, merged