Navigator Refactoring
endavainterns2016/WeatherApp pull request #44
Opened 2016-12-02 10:34 UTC by CebotariM

2016-12-02 11:56 UTC, MaximCeban requested changes

2016-12-02 11:56 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/design/WeatherCodesMap.java
> +    private final int iconResIndex;
there is no reason to assign this variable with value in constructor, in this case is better to use constant instead just final variable that is initialized in  constructor. the same for the variable below.

2016-12-02 11:56 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/navigator/Navigator.java
> +    public Navigator toClass(Class target) {
could you please try to use more meaningful name for this method.

2016-12-02 11:56 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/navigator/Navigator.java
> +        this.sentBundle = new Bundle();
unfortunately this class is untestable be careful please.

2016-12-02 21:06 UTC, MaximCeban requested changes

2016-12-02 21:06 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/design/WeatherCodesMap.java
> +    private static final int iconResIndex = 0;
http://www.oracle.com/technetwork/java/codeconventions-135099.html

2016-12-02 21:06 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/sharedpreferences/SharedPrefs.java
> +        this.editor = preferences.edit();
there is no reason to store editor, you can call it in each method. please avoid storing link to unused class.

2016-12-07 14:02 UTC, CebotariM commented on app/src/main/java/com/example/nvdovin/weatherapp/domain/utils/navigator/Navigator.java
> +        this.sentBundle = new Bundle();
The class uses native Android Packages (Intent) and cannot be tested

2016-12-08 07:47 UTC, MaximCeban approved these changes

2016-12-08 07:48 UTC, merged