Add recyler view
endavainterns2016/WeatherApp pull request #6
Opened 2016-10-28 14:02 UTC by CebotariM

Added RecyclerView on main screen. To Add images as background

2016-10-28 14:07 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/ForecastActivity.java
> +    Integer tempScale = 273;
Max please pay attention to 
http://www.oracle.com/technetwork/java/codeconventions-135099.html

2016-10-28 15:09 UTC, victorjimbei requested changes

2016-10-28 15:09 UTC, victorjimbei commented on app/src/main/res/layout/forecast_recycler_row.xml
> +    android:paddingBottom="30dp"
please move all hardcoded dimensions in dimens file.

2016-10-28 15:09 UTC, victorjimbei commented on app/src/main/java/com/example/nvdovin/weatherapp/adapter/SeparatorDecoration.java
> +    Paint paint;
add please access modifiers

2016-10-28 15:09 UTC, victorjimbei commented on app/src/main/java/com/example/nvdovin/weatherapp/adapter/SeparatorDecoration.java
> +    Paint paint;
Add please access modifiers.

2016-10-28 15:09 UTC, victorjimbei commented on app/src/main/java/com/example/nvdovin/weatherapp/ForecastActivity.java
> +    RecyclerView recyclerView;
Add please access modifiers.

2016-10-28 15:09 UTC, victorjimbei commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait"></activity>
Try to avoid xml tag empty body.

2016-10-31 07:44 UTC, MaximCeban requested changes

2016-10-31 07:44 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/adapter/SeparatorDecoration.java
> +        final int offset = (int) (paint.getStrokeWidth() / 2);
what does it mean "2", use constant and give meaningful name

2016-10-31 07:44 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/ForecastActivity.java
>      float separatorHeight = 5.5f;
try to avoid using variable for layout dimention in java class, use  resources instead

2016-10-31 07:44 UTC, MaximCeban commented on app/src/main/java/com/example/nvdovin/weatherapp/ForecastActivity.java
>      int tempScale = 273;
Use constant instead of simple variable. pay attention on http://www.oracle.com/technetwork/java/codeconventions-135099.html

2016-11-01 11:45 UTC, closed without merging